// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Wed Mar 20 23:51:53 2019

SAFEV SAFEV_inst
(
	.CLOCK_50(CLOCK_50_sig) ,	// input  CLOCK_50_sig
	.hlt(hlt_sig) ,	// output  hlt_sig
	.reg_write(reg_write_sig) ,	// output  reg_write_sig
	.mem_reg(mem_reg_sig) ,	// output  mem_reg_sig
	.mem_write(mem_write_sig) ,	// output  mem_write_sig
	.alu_src(alu_src_sig) ,	// output  alu_src_sig
	.branch(branch_sig) ,	// output  branch_sig
	.instruction(instruction_sig) 	// output [31:0] instruction_sig
);

